spring:
  application:
    # ????
    name: KafkaEasyStudy
    # kafka????(ip+??)
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    # ?????
    producer:
      value-serializer: org.springframework.kafka.support.serializer.ToStringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
#      auto-offset-reset: latest


    # 配置模版默认的主题topic名称
    template:
      default-topic: default-topic


